name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop  
  workflow_dispatch:
    inputs:
      env:
          type: choice
          description: Select Environment
          required: true
          options:
            - main
            - develop
        




jobs:
  build_project:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
      - name: Login to AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-south-1 

      - name: Push build artifacts to S3 bucket
        run: aws s3 cp ./build s3://staticwebhosting476
